БЛР1 P3334 Бахилин Никита
bakhilin/os-shell-benchmarks pull request #3
Opened 2024-11-27 09:29 UTC by bakhilin

P3334 Бахилин Никита
Базовый трек, оценка 4. ЛР 1. Shell
Вариант: Linux, ema-sort-str, sort

## Описание изменений

Реализовал Shell в модуле shell.c utils.c, добавил тесты.

2024-11-27 10:09 UTC, vityaman requested changes
Прикольно. Давайте только `search-str` перепишем.

2024-11-27 10:09 UTC, vityaman commented on src/c/ema_search_str.c
Это должен быть алгоритм поиска подстроки в строке во внешней памяти. Вы тут не читаете файл совсем.

2024-11-27 10:09 UTC, vityaman commented on src/c/utils.c
> +#define SHELL_PRINT printf("bakhilin@shell:")
А почему бы не написать это as is? Зачем макрос?

2024-11-27 20:47 UTC, bakhilin commented on src/c/utils.c
> +#define SHELL_PRINT printf("bakhilin@shell:")
Последние два макроса соглашусь, лишнее. А вот первые, мне кажется, привносят ясность в код

2024-11-27 20:50 UTC, bakhilin commented on src/c/ema_search_str.c
fixed

2024-11-28 05:21 UTC, vityaman commented on src/c/utils.c
> +#define SHELL_PRINT printf("bakhilin@shell:")
Согласен

2024-11-28 05:23 UTC, vityaman commented on src/c/ema_search_str.c
> +}
Вы читаете файл полностью, а по ТЗ нужно блоками.

2024-11-29 05:41 UTC, vityaman approved these changes
С вас качественное исследование (мониторинг) поведения написанных бэнчмарков.

2024-11-30 04:47 UTC, vityaman commented
Нормально, теперь все правильно. Теперь нужно промониторить все это дело.

2024-11-30 06:50 UTC, bakhilin commented on src/c/utils.c
> +}
fixed @vityaman

2024-12-01 16:38 UTC, vityaman approved these changes

2024-12-04 13:18 UTC, vityaman approved these changes
Нормасно, кул!

2024-12-04 13:18 UTC, vityaman commented on src/c/controller.c
> +#include "../include/utils.h"
ИМХО, лучше не использовать .. в инклюдах -- это сложно читать. Лучше использовать пути от корня проекта. Исключения: инклюд парного хэдера и хэдеров из текущей директории.

Есть, кстати, кодстайлы всякие. Например, яндексовый: https://github.com/yandex/CMICOT/blob/master/CPP_STYLE_GUIDE.md#include

2024-12-04 13:18 UTC, vityaman commented on src/c/controller.c
> +    int reps = atoi(argv[1]);
А что будет если `argv[1] == "zhopa"`?

2024-12-04 13:18 UTC, vityaman commented on src/c/controller.c
> +    p.filename = filename;
Кажется, можно было сразу из `argv` проинициализировать поля.

2024-12-04 13:18 UTC, vityaman commented on src/c/controller.c
> +    pthread_create(&threads[1], NULL, load_data_from_file, (void *)&p);
А если создание треда завершится с ошибкой?

2024-12-04 13:18 UTC, vityaman commented on src/c/controller.c
> +        pthread_join(threads[i], NULL);
Тут тоже ошибка может быть.

2024-12-04 13:18 UTC, vityaman commented on src/c/sort.c
> +        pthread_create(&threads[i], NULL, sort_load, r);
Давай уберем ненужные комментарии.

2024-12-04 13:18 UTC, vityaman commented on src/c/utils.c
> +    while (1) {
Кстати, более идиоматично: `for(;;) { .. }`

2024-12-04 13:18 UTC, vityaman commented on src/c/utils.c
> +            long total_microseconds = seconds * 1000000 + microseconds;
Can be made const.

2024-12-04 13:18 UTC, vityaman commented on src/c/utils.c
> +            gettimeofday(&end_time, NULL);
fallible

2024-12-04 13:18 UTC, vityaman commented on src/c/utils.c
>          } else {
Этот else можно убрать. У нас же `break`. Лучше понизить уровень вложенности.

2024-12-04 13:18 UTC, vityaman commented
Доп нужно выдать? Без допа макс 12 баллов.

2024-12-04 19:35 UTC, bakhilin commented on src/c/controller.c
> +    int reps = atoi(argv[1]);
ахаха

2024-12-04 19:35 UTC, bakhilin commented on src/c/controller.c
> +    int reps = atoi(argv[1]);
будет жопа)

2024-12-04 21:12 UTC, bakhilin commented on src/c/controller.c
> +    int reps = atoi(argv[1]);
fixed @vityaman

2024-12-04 21:12 UTC, bakhilin commented on src/c/controller.c
> +    p.filename = filename;
fixed @vityaman

2024-12-04 21:13 UTC, bakhilin commented on src/c/sort.c
> +        pthread_create(&threads[i], NULL, sort_load, r);
fixed @vityaman

2024-12-04 21:13 UTC, bakhilin commented on src/c/utils.c
> +    while (1) {
fixed @vityaman

2024-12-04 21:13 UTC, bakhilin commented on src/c/utils.c
> +            long total_microseconds = seconds * 1000000 + microseconds;
fixed @vityaman

2024-12-04 21:13 UTC, bakhilin commented on src/c/utils.c
>          } else {
fixed @vityaman

2024-12-04 21:13 UTC, bakhilin commented on src/c/utils.c
> +            gettimeofday(&end_time, NULL);
не понял

2024-12-05 08:06 UTC, vityaman commented on src/c/utils.c
> +            gettimeofday(&end_time, NULL);
Может завершиться с ошибкой.

2024-12-21 08:56 UTC, vityaman requested changes

2024-12-21 08:56 UTC, vityaman commented on src/c/controller.c
> +}
А в чем смысл открывания и закрывания файла? У вас есть гарантии, что он после этого не исчезнет?

2024-12-21 08:56 UTC, vityaman commented on src/c/controller.c
> +        argv[2] == "zhopa" ||
?)

2024-12-21 08:56 UTC, vityaman commented on src/c/controller.c
> +    for (int i = 0; i < 2; i++) {
Давайте размер массива с потоками вынесем в константу или каким-то другим способом решим проблему того, что количество итераций этого цикла не соотносится с реальным размером массива (если изменим массив, а тут забудем, будет баг).

2024-12-21 08:56 UTC, vityaman commented on src/c/ema_search_str.c
> +    p.reps = repetitions;
Как насчет использования инициализатора? Я про создание инициализацию структуры при помощи фигурных скобок.

2024-12-21 08:56 UTC, vityaman commented on src/c/utils.c
> +        wait(NULL);
Не может завершиться с ошибкой?

2024-12-21 08:56 UTC, vityaman commented on src/c/utils.c
> +    return (void*)(__intptr_t)found;
Почему к такому интересному типу кастим?

2024-12-21 08:56 UTC, vityaman commented on src/c/utils.c
> +    FILE * file = fopen(filename, "w");
А если ошибка...

2025-01-22 13:15 UTC, merged

2025-01-22 13:15 UTC, bakhilin commented on src/c/controller.c
> +        argv[2] == "zhopa" ||
Ахахахахах